### PR TITLE
More consistence in configuration fields

### LINKED ISSUE #24: stucture::optionFromField that cares about capital letters
Hello guy,
Thanks for this work, this is really great.

I have an idea that I'd want to implement in gonfig but I want to have your advice first.

The optionFromField function takes the field name and build the id from it using this code : 
```
        id := f.Tag.Get(fieldTagID)
	if len(id) == 0 {
		id = strings.ToLower(f.Name)
	}
	opt.id = id
```

Problem is when I have for example the struct field ``LogLevel``, I'd want my config file corresponding field to be ``log_level``.

I can obviously define my struct field like that
```
type ServerConfiguration struct {
	Port int 		`env:"SERVER_PORT" default:"8080"`
	LogLevel string `toml:"log_level" env:"SERVER_LOG_LEVEL" default:"<root>=ERROR"`
}
```

But I'd prefer to count on a default behaviour.
There I have an issue, what to choose as default behavior : 
- snake case : ``log_level``
- camel case : ``logLevel``

Maybe we could use as default what you already implemented, but have the possibility to override it in the ``gonfig.Conf`` what do you think about it ?

See you !

### PR DESCRIPTION
**Pull request by celian-garcia**
Closes #24 

The plan is to integrate the possibility to have more flexible configuration fields formats in : 
- configuration files (toml, yaml & json)
- flags parameters (--config-file --my-var ...)
- environment variables (MY_ENV_VAR)

To do this, ``opt.id`` and ``opt.fullIds`` fields should contain the information of the position of differents marker '-', '_', '<capital letter>'. To do this, we'll simply use a classic "kebab-case" format to save ids 

Plan : 
- [x] opt.id and opt.fullIds in a "kebab-case" format 
- [x] flags parameter --my-var can fill ``MyVar`` option field.
- [ ] **[keep the legacy]** flags parameter --myvar can still fill ``MyVar`` option field.
- [x] environment variable MY_VAR can fill ``MyVar`` option field.
- [ ] **[keep the legacy]** environment variable MYVAR can still fill ``MyVar`` option field.
- [x] config file parameter my-var or my_var or myVar can fill ``MyVar`` option field.
- [ ] **[keep the legacy]** config file parameter myvar can still fill ``MyVar`` option field.
- [x] Documentation [variables syntax](https://github.com/celian-garcia/gonfig/blob/configuration_fields_cases/docs/variables_syntax.md)

### CODE REVIEW

**Comment by stevenroose** [comment]
The problem with the mixed case thing is that in config files and env vars, we only go from id to the key, not the opposite way around. I think this would only be possible by significantly changing how gonfig works. I think being explicit is better.

**Comment by celian-garcia** [comment]
I can do a non mixed case code but if I do that, it will certainly be a breaking change :/
I did not want to break the current interface. 

What I can do for the moment is to follow some explicit guidelines : 
- configuration file : snake_case
- flags parameters : kebab-case
- env variables : SCREAMING_SNAKE_CASE

And see after if I can be more flexible in order to at least not break the interface.

**Comment by celian-garcia** [comment]
Hello steven, I finished the code but the legacy has not been kept :/ **Please have a look at the not ticked checkboxes (legacy ones) and say me if it is ok for you.**

I need your opinion also about the **env variables** for nested structures. Cf last comment edit: 
> Edit: for env variables, a SCREAMINGJOINTCASE like what is already implemented is more readable for nested structures like this MYVAR_MYNESTEDVAR (more readable than MY_VAR_MY_NESTED_VAR)

For me it remains only the documentation update that I will do soon.

**Comment by costela** [comment]
Hi, sorry for barging in on the discussion, but I wanted to give my 2 cents as a fellow user/contributor.

I'm not sure about the cost/benefit of adding this complexity. It feels like a lot of code (+~180 loc in a ~2200 loc project; around 8%) for a mostly aesthetic feature.
Additionally, I'm no convinced the ambiguity of being able to write config in multiple formats is something we should be striving for. Case-insensitivity might be acceptable or even desirable, but having something like `-Ugly--Mixed-_--case_-` (taken from the current tests) feels like crossing an unnecessary line.
IMHO we should be moving in the opposite direction: make config parsing more strict and be more verbose about options that don't map to anything in the struct (adding something like `FileIgnoreUnknown`, backed by e.g. `json.Decoder.DisallowUnknownFields()` and `yaml.UnmarshalStrict()`).

**Comment by stevenroose** [comment]
Yeah like my earlier comment suggested, I think I agree with @costela. I don't think having mixed-case variables makes any sense in a system where env vars are always caps and cli flags are always lowercase.

@celian-garcia, thanks for the PR, though!

**Comment by celian-garcia** [comment]
I totally agree with both of you, you focus on mixed case feature but it was just a consequency of the code. What I wanted to do first was to keep the word separation information.

For example, What I found weird when I first used gonfig was when you define a config variable like MyVariable, you fill it with 'myvariable'. I spent a time to understand that m'y field 'my-variable' in my config file would have not any effect ^^

**Comment by celian-garcia** [comment]
Did you look at the documentation I wrote ? Which summarize all I said https://github.com/celian-garcia/gonfig/blob/configuration_fields_cases/docs/variables_syntax.md

**Comment by stevenroose** [comment]
Hmm, one think that could lead to confusion is that when you have two keys
in a file `my_var` and `my-var`, the last one would overwrite the other. Or
if it's a slice argument and one of them has a CSV `my_var: ["a", "b"]` and
`my-var: "c"`, the interpreter could see that as you trying to create a
slice likes this `['["a", "b"]', 'c']`.

**Comment by celian-garcia** [comment]
Yeah you're right, the simplest way to deal with that would be to panic with a clear message when two field of config file try to fill the same option. I can make some tests to ensure this behavior.

**Comment by celian-garcia** [comment]
Okay guys, you know what I'll give up this time ^^ Hope you understood my point but I have no more time to ameliorate this. If you are okay I'll close this PR.
Bye and thank you for your time !

**Pull request closed without merging**
