### PR TITLE
Adding support for time.Duration

### PR DESCRIPTION
**Pull request by raff**
For some reason time.Time implements TextUnmarshaler, but time.Duration doesn't (and it's actually quite useful)

### CODE REVIEW

**Comment by zbindenren** [comment]
+1

**Comment by stevenroose** [comment]
Yeah I noticed that time.Duration didn't. In principle, I'd prefer to avoid adding specific types to be supported. You could add something like 
```go
type EncodedDuration time.Duration

func (e *EncodedDuration) UnmarshalText(t []byte) error {
	d, err := time.ParseDuration(string(t))
	if err != nil {
		return err
	}
	*e = d
	return nil
}
```

I do those all the time with binary values that I need to have encoded as hexadeximal instead of base64.

**Comment by zbindenren** [comment]
I could live with that.

**Comment by stevenroose** [comment]
I'm gonna close this. I've added several new features, like `map[string]interface{}` support. I also removed the pflag dependency and implemented custom flag parsing and help messages.

**Pull request closed without merging**
