### PR TITLE
set default for all options, not only top-level

### LINKED ISSUE #26: default values in nested struct
Hey,

Either I misunderstood something fundamental about `gonfig`, or there might be a bug with default values and nested structs: the default values seem to be completely ignored.

```go
package main

import (
	"fmt"
	"github.com/stevenroose/gonfig"
)

var conf = struct {
	A string `default:"foo"`
	B struct {
		C string `default:"bar"`
	}
}{}

func main() {
	err := gonfig.Load(&conf, gonfig.Conf{})
	if err != nil {
		panic(err)
	}

	fmt.Printf("A: %s, C: %s\n", conf.A, conf.B.C)
}
```
And then:
```
$ go run tmp.go
A: foo, C:
```
(expected `A: foo, C: bar`)

This is a bit unexpected because setting the value explicitly works:
```
$ go run tmp.go --b.c baz
A: foo, C: baz
$ B_C=baz go run tmp. go
A: foo, C: baz
```

Am I missing something obvious?

### PR DESCRIPTION
**Pull request by costela**
one-liner to fix #26  :wink:

### CODE REVIEW

**Comment by stevenroose** [comment]
You're amazing!

**Comment by costela** [comment]
Not sure what's going on with the builds though :/
go1.9 is green, all the other have what appears to be unrelated issues?

**Comment by stevenroose** [comment]
Yeah I noticed I didn't update to modules yet. Haven't done much Go since they introduced modules. Should I add the mod file? This project is still doing dep.

**Comment by costela** [comment]
I can gladly take a shot at that if you want. Actually, probably not a bad idea to add a simple test-case for this PR either... :sweat_smile:

**Comment by costela** [comment]
So, test-case added and with the mod files everything looks green! :tada:

**Comment by stevenroose** [comment]
Could you rebase on master so that there is only your two new commits? I added 1.7 and 1.8 again but disabled linting for all older versions.

**Comment by costela** [comment]
done! :heavy_check_mark:

**Comment by stevenroose** [comment]
Lovely! I'll tag v0.1.2 as well.

**Pull request merged**
